### ISSUE TITLE
FOV not working correctly

### ISSUE THREAD

**Issue by sasvdw** [LazyGameDevZA/RogueDOTS#1]
At present tests prove that FOV is working correctly with a radius of up to 3. The current setup has the player's viewshed set to 8 which is yielding strange deadspots in the FOV. See the image below for more detail. The image does clearly show a floor tile that's considered not visible yet it's surrounded by visible floor tiles.

![image](https://user-images.githubusercontent.com/8395822/73213657-3d9fd080-4159-11ea-8f25-e557ec361c1f.png)

**Comment by sasvdw** [comment]
I'm starting to believe that this is due to a difference in how  C# is casting `float` values compared to Rust. The documentation for both languages states that casting a `float` to `int` would always round to zero. Some testing on this [dotnetfiddle](https://dotnetfiddle.net/5BTCC1)  confirms that  C# is definitely rounding to zero.

**Comment by sasvdw** [comment]
Closer inspection on the tutorial is showing that it's suffering from the same issue. I'm still leaving this as a bug that can be fixed in case anybody else wants to give it a bash.

**Comment by mattpwest** [comment]
I have started by reading up a bit about Roguelike FOV algorithms (very nice comparison here: http://roguebasin.roguelikedevelopment.org/index.php?title=Comparative_study_of_field_of_view_algorithms_for_2D_grid_based_worlds).

Long story short, BASIC looks like a decent first option to implement...

I'm guessing that's already the implementation you got from RLTK - suspect it's just the post-processing step that's missing. Here's a good description of the algorithm: https://sites.google.com/site/jicenospam/visibilitydetermination

I'll try and write a failing test tomorrow and then see if I can add a fix.

**Comment by mattpwest** [comment]
Sorry, only just got back to this and noticed another problem. Even with my ugly Bresenham artefact fixing code in place, there are still some dead spots within the view radius - on the floor.
![image](https://user-images.githubusercontent.com/6697562/73689010-9200fe00-46cd-11ea-9d3e-100bbee35133.png)

At least some of that is directly on the diagonal, which leads me to guess that part of the problem is that we're not casting enough rays - perhaps due to using a Bresenham circle as the target set? I can imagine that for certain radii the direct diagonal might not be one of the pixels we draw a line to, which would mean only some of the diagonal is getting covered by approximation of the nearby lines.

I am quickly going to try using a rectangle as the target set instead hopefully if that improves it. Then I'll go back to working on making the postprocessing algorithm generic.
