### ISSUE TITLE
Level generation: leftmost wall edge case

### ISSUE THREAD

**Issue by mattpwest** [LazyGameDevZA/RogueDOTS#4]
While testing my vision fix I ran into the following scenario: looks like the level generator generated a room that fell off the left edge of the map. Probably just an incorrect edge-case somewhere:

![image](https://user-images.githubusercontent.com/6697562/73716841-74a55180-4718-11ea-98f1-1d5045de3f1d.png)

Would you consider any of the following changes to make things like this easier to troubleshoot:
- Add a proper logging library (ideally, one that could be configured to log to file and to Unity)
- Add a way to seed the level generator (maybe through config file or an environment variable)

My thinking is that if we could go check a log to see the level seed that was generated and then re-generate using that seed it would make it very easy to reproduce (and hopefully) fix problems like this.

**Comment by sasvdw** [comment]
Unity's logging should work well enough. I am aware of this, but it seems that the tutorial also suffers from this issue. For now, I don't see it as too much of a problem as I was planning on doing a later pass to add more extensive logging that can include level seeds etc.

**Comment by sasvdw** [comment]
It does appear as though this is present in the tutorial's code as well (see screenshot below). I'm marking this as a bug for anybody to be looked at. I'm going to keep focusing more on getting more functionality done rather than bashing all the bugs. 7DRL is around the corner and having more to work with would be better in my view.

![Screenshot 2020-02-04 at 14 35 30](https://user-images.githubusercontent.com/8395822/73745450-ba373e00-475b-11ea-8342-40a93268e213.png)
